In [14]:
import numpy

In [15]:
x2 = numpy.arange(12).reshape(3,4)
matrix = numpy.array([x2, x2], dtype=int)

In [18]:
matrix

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [29]:
matrix.sum(axis=1).sum(axis=0)

array([24, 30, 36, 42])

In [24]:
matrix[0].sum(axis=1)

array([ 6, 22, 38])

In [17]:
matrix.sum(axis=0)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [30]:
matrix.sum(axis=1)

array([[12, 15, 18, 21],
       [12, 15, 18, 21]])

In [31]:
matrix.shape

(2, 3, 4)